default:
  lag: 70
  predict_range: 15
  date_format: "%Y-%m-%d"
  email_recipients:
    - wkawi@sertiscorp.com
    - jjira@sertiscorp.com
    - nontanat.toc@axonstech.com
    - jirapast.bun@axonstech.com
  directories:
    other_dataset_path: other_dataset
    unprocessed_dataset_path: unprocessed_dataset
    training_dataset_path: processed_dataset/training
    testing_dataset_path: processed_dataset/testing
    models_path: models
    raw_predictions_path: predictions/raw
    processed_predictions_path: predictions/processed
    evaluation_results_path: results/evaluation
    data_validation_reports_path: results/data_validation
  data_types:
    - name: very_dense
      mae_threshold: 70.0
    - name: dense
      mae_threshold: 30.0
    - name: sparse
      mae_threshold: 25.0
    - name: very_sparse
      mae_threshold: 3.0
  features:
    - dayOfWeek_TE
    - day
    - month_TE
    - year
    - Density_category_TE
    - WarehouseBKey_TE
    - ProductBKey_TE
    - UMForecastQty_TE
    - ForecastAccount_TE
    - CustomerBKey_TE
    - SalesExc
  label_column_name: OrderPlanningUnit
  predict_column_name: Predict
  evaluate_interval: 14 # days
  evaluate_cols:
    - key
    - DayKey
    - OrderPlanningUnit
    - Predict
  final_result_schema:
    key: STRING
    DayKey: DATE
    WarehouseBKey: STRING
    UMForecastQty: STRING
    ProductBKey: STRING
    ForecastAccount: STRING
    CustomerBKey: STRING
    ProductForPlan1: STRING
    density: FLOAT64
    Density_category: STRING
    MinDate: STRING
    Predict: FLOAT64
    rounded: FLOAT64
    GeneratedDate: TIMESTAMP
  src_dir: src
  pipeline_template_dir: pipeline_templates
  pipeline_template_file_name: demand_forecast_pipeline_dev.json

development:
  project_id: axon-aiml-sertis
  region: us-central1
  pipeline_sa: axon-aiml-sertis-sa@axon-aiml-sertis.iam.gserviceaccount.com
  base_image: us-central1-docker.pkg.dev/axon-aiml-sertis/daily-demand-forecast-pipeline/pipeline-base:latest
  gcs:
    bucket_name: cpf-mlops-daily-demand-forecast-pipeline-dev
    bucket_uri: gs://cpf-mlops-daily-demand-forecast-pipeline-dev
    root_dir: /gcs/cpf-mlops-daily-demand-forecast-pipeline-dev
    pipeline_root_dir: pipeline_root
  bq:
    dataset_id: axon-aiml-sertis.sample_data
    demand_table_name: DemandForecast_Daily_WetMarket_snapshot_noKey
    product_table_name: DimProduct
    forecast_account_table_name: ForecastAccount_total_Copy
    unitconv_table_name: V_UnitConversionPack
    final_result_table_name: production_table
